version: '3'
services:

  # Port list
  #
  # - Scoreboard -
  #
  # 80    Nginx
  # 443   Nginx
  # 8000  CTFd
  #
  # - Challenges -
  #
  # 9000  Talk to me launcher
  # 9001  License server
  # 9002  Evilcorp login server
  # 9003  Evilcorp server
  # 9004  Evilcorp server SSH
  # 9005  Go With The Flow Server
  # 9006  Phone Access server


  # Nginx
  nginx-ssl-proxy:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    environment:
      SERVERNAME: scoreboard.h4tt.ca
      EXTRANAMES: evilcorp.h4tt.ca
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
    networks:
      default:

  # CTFd
  ctfd:
    image: ctfd/ctfd
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
      default:
      ctfd:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    networks:
      ctfd:

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
      ctfd:

  # Challenges

  # talk-to-me-launcher:
  #   build:
  #     dockerfile: servers/talk_to_me/Dockerfile
  #     context: ../
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   ports:
  #     - "9000:22"
    
  # talk-to-me-challenge:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ../pwn/talk_to_me/challenge
  #   entrypoint: "bash -c"
  #   command: "exit 0"

  license-server:
    build:
      dockerfile: servers/license/Dockerfile
      context: ../
    ports:
      - "9001:1337"
    networks:
      default:

  evilcorp-login-server:
    build:
      dockerfile: servers/evilcorp_login_server/Dockerfile
      context: ../
    ports:
      - "9002:1337"
    networks:
      default:

  evilcorp-server:
    build:
      dockerfile: servers/evil_corp/Dockerfile
      context: ../
    ports:
      - "9003:3000" # Server
      - "9004:22"   # SSH
    networks:
      default:

  go-with-the-flow-server:
    build:
      dockerfile: servers/go_with_the_flow/Dockerfile
      context: ../
    ports:
      - "9005:9000"
    networks:
      default:

  phone-access-server:
    build:
      dockerfile: servers/phone_access_server/Dockerfile
      context: ../
    ports:
      - "9006:1337"
    networks:
      default:

networks:
    default:
    ctfd:
      internal: true