version: '3'
services:

  # Port list
  #
  # - Scoreboard -
  #
  # 80    Nginx
  # 443   Nginx
  # 8000  CTFd
  #
  # - Challenges -
  #
  # 9000  
  # 9001  
  # 9002  
  # 9003  
  # 9004  
  # 9005  


  # Nginx
  nginx-ssl-proxy:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    environment:
      SERVERNAME: scoreboard.h4tt.ca
      EXTRANAMES: evilcorp.h4tt.ca
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
    networks:
      default:

  # CTFd
  ctfd:
    image: ctfd/ctfd
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
      default:
      ctfd:

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    networks:
      ctfd:

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
      ctfd:

  # Challenges
  talk-to-me-launcher:
    build:
      dockerfile: servers/talk_to_me/Dockerfile
      context: ../
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:22"
    
  talk-to-me-challenge:
    build:
      dockerfile: Dockerfile
      context: ../pwn/talk_to_me/challenge
    entrypoint: "bash -c"
    command: "exit 0"

networks:
    default:
    ctfd:
      internal: true